api2doc: 
  title: 金丰供应链系统API接口文档

server:
  port: 8090

logging:
  config: classpath:log4j2.xml

spring:
    application:
        name: sdms
    #pringboot上传文件大小的配置
    http.multipart.maxFileSize: 10Mb  
    http.multipart.maxRequestSize: 50Mb       
    datasource:
        name: sdms_datasource
        url: jdbc:mysql://localhost:3306/sdms_db?useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: scdp
        password: ccz@dbt888
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall
        maxActive: 20
        initialSize: 1
        #配置获取连接等待超时的时间
        maxWait: 60000
        minIdle: 1
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
        testWhileIdle: true
        #获取连接时执行检测，建议关闭，影响性能
        testOnBorrow: false
        testOnReturn: false
        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
        poolPreparedStatements: false
        #开启poolPreparedStatements后生效
        maxPoolPreparedStatementPerConnectionSize: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
        
        # 配置日志输出
        filter:
          slf4j:
            enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.honest.sdms.*.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql